
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"
import { FoodProvider } from "@/providers/foodItemProvider";
import { AuthTrainerProvider } from "@/providers/authProvider/trainer";
import { CurrentUserProvider } from "@/providers/currUserProvider";
import { ClientManProvider } from "@/providers/ClientManProvider";
import { ClientAuthProvider } from "@/providers/authProvider/client";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    
      <body className={`${geistSans.variable} ${geistMono.variable}`}>

      <AuthTrainerProvider>
      <CurrentUserProvider>
      <ClientManProvider>
       <ClientAuthProvider>
        <FoodProvider>
        {children}
      </FoodProvider>
      </ClientAuthProvider>
      </ClientManProvider>
      </CurrentUserProvider>
     </AuthTrainerProvider>
      </body>
   
    </html>
  );
}
